version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directory: "/dispatch-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/pricing-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/trip-service"
    schedule:
      interval: "weekly"
